---
title: "fyp_2_analysis"
output: html_document
---
```{r}
library(rjson)
library(ggplot2)
library(tidyr)
library(dplyr)
library(lme4)
library(lmerTest)
```

#Read files:
```{r}
data_location = "../data/fyp_2_data/" 
files = list.files(path = data_location,pattern="data_subject_.*.json")
modular_data = vector()
polygon_data = vector()
hybrid_data = vector()
#data frame building
subject = vector()
prompt = vector()
correct_response = vector()
rt = vector()
response = vector()
condition = vector()
trial_index = vector()
score = vector()

j = 1
for (i in 1:length(files)) {
  path = paste(data_location,files[i],sep="")
  print(i)
  print(path)
  c = file(path, "r")
  l = readLines(c, -1L)
  close(c)
  these_data = lapply(X=l, fromJSON)
  if (these_data[1][[1]][[1]]$trial_type == "instructions") {
      this_condition = "modular"
      modular_data[length(modular_data) + 1] = these_data[1]
  } else {
    if (grepl("subtract",gsub(" ","",these_data[1][[1]][[1]]$instructions))) { 
        this_condition = "hybrid"
        hybrid_data[length(hybrid_data) + 1] = these_data[1]
    }
    else {
       this_condition = "polygon"
       polygon_data[length(polygon_data) + 1] = these_data[1]
    }
  }
  
  for (trial_i in 1:length(these_data[1][[1]])) {
    if(grepl("question",gsub(" ","",these_data[1][[1]][[trial_i]]$trial_type))) {
      subject[j] = i
      condition[j] = this_condition
      prompt[j] = these_data[1][[1]][[trial_i]]$question
      correct_response[j] = these_data[1][[1]][[trial_i]]$correct_response
      
      if (is.null(these_data[1][[1]][[trial_i]]$response)) {
        response[j] = NA
      }
      else {
        response[j] = these_data[1][[1]][[trial_i]]$response
      }
      
      if (!is.na(response[j]) && response[j] == correct_response[j]) {
        score[j] = 1
      } else {
        score[j] = 0        
      }
      rt[j] = these_data[1][[1]][[trial_i]]$rt
      trial_index[j] = trial_i
      
      j = j+1
    }
  }
}
```

Write data for scoring
----------------------------

```{r}
#complete_data = data.frame(subject=factor(subject),condition=condition,question=prompt,correct_response=correct_response,response=response,rt=rt,trial_index=trial_index,score=score) 

##n=9 operation questions
#write.table(complete_data[(grepl("Whatis8",gsub(" ","",complete_data$question)) | grepl("Whatis4",gsub(" ","",complete_data$question)))& grepl("explaininwords",gsub(" ","",complete_data$question)) ,c(1,3,4,5,7)],"N9_operation_to_score.csv",sep=",")

##n=9 generator questions
#write.table(complete_data[grepl("generatorunder",gsub(" ","",complete_data$question)) & (grepl("nonagon",gsub(" ","",complete_data$question)) | grepl("+<sub>9",gsub(" ","",complete_data$question)) ),c(1,3,4,5,7)],"N9_generator_to_score.csv",sep=",")

##n=9 inverse with explanations
#write.table(complete_data[grepl("inverseof3",gsub(" ","",complete_data$question)) & (grepl("nonagon",gsub(" ","",complete_data$question)) | grepl("+<sub>9",gsub(" ","",complete_data$question)) ),c(1,4,5,7)],"N9_inverse_to_score.csv",sep=",")

##generator T/F and A/S/N with explanations
#write.table(complete_data[grepl("explaininwords",gsub(" ","",complete_data$question)) & (grepl("Trueorfalse",gsub(" ","",complete_data$question)) | grepl("always,sometimes,ornever",gsub(" ","",complete_data$question))),c(1,4,5,7)],"TF_ASN_explained_to_score.csv",sep=",")

##n-1,n-x
#write.table(complete_data[grepl("formula",gsub(" ","",complete_data$question)),c(1,4,5,7)],"inverse_formula_to_score.csv",sep=",")
```

data frame building
------------------------
```{r}
complete_data = data.frame(subject=factor(subject),condition=condition,question=prompt,correct_response=correct_response,response=response,rt=rt,trial_index=trial_index,score=score)  

#Insert scored data
inverse_formula_scores = read.csv(paste(data_location,"inverse_formula_scored.csv",sep=""))
complete_data[inverse_formula_scores$row.names,]$score = inverse_formula_scores$score

TF_ASN_explained_scores = read.csv(paste(data_location,"TF_ASN_explained_scored.csv",sep=""))
complete_data[TF_ASN_explained_scores$row.names,]$score = TF_ASN_explained_scores$score

N9_operation_scores =read.csv(paste(data_location,"N9_operation_scored.csv",sep=""))
complete_data[N9_operation_scores$row.names,]$score = N9_operation_scores$score
N9_operation_scores[grepl("Whatis4",gsub(" ","",N9_operation_scores$question)),]$correct_response = 5
N9_operation_scores[grepl("Whatis8",gsub(" ","",N9_operation_scores$question)),]$correct_response = 3
complete_data[N9_operation_scores$row.names,]$correct_response = N9_operation_scores$correct_response #omitted because of answer explanation

N9_generator_scores = read.csv(paste(data_location,"N9_generator_scored.csv",sep=""))
complete_data[N9_generator_scores$row.names,]$score = N9_generator_scores$score

N9_inverse_scores =read.csv(paste(data_location,"N9_inverse_scored.csv",sep=""))
complete_data[N9_inverse_scores$row.names,]$score = N9_inverse_scores$score
complete_data[N9_inverse_scores$row.names,]$correct_response = 6 #omitted because of answer explanation

#Strict scoring -- Some questions have "partial credit" of 0.5 for almost correct answers
complete_data = complete_data %>% mutate(score_strict = floor(score)) 


```

Demographic analyses
-----------------------
###condition 
```{r}
ggplot(data = complete_data[grepl("isyourage?",gsub(" ","",complete_data$question)),], aes(condition)) +
  geom_histogram() +
  labs(x="condition",y="frequency",title="Condition histogram") +
  theme_bw()

```

????

###Age
```{r}
ggplot(data = complete_data[grepl("isyourage?",gsub(" ","",complete_data$question)),], aes(as.numeric(levels(response))[response])) +
  geom_histogram() +
  labs(x="age",y="frequency",title="Age histogram") +
  theme_bw()

```

###gender
```{r}
summarized_data = complete_data[grepl("gender",gsub(" ","",complete_data$question)),] %>% group_by(subject) %>% summarize(gender = gsub(" ","",response))
summarized_data = replace(summarized_data,is.na(summarized_data),'Did not respond')
ggplot(data = summarized_data, aes(gender,fill=gender)) +
  geom_bar() +
  labs(x="Gender",y="frequency",title="Gender histogram")+
  theme_bw()

```

###Native Language

```{r}
summarized_data = complete_data[grepl("nativelanguage",gsub(" ","",complete_data$question)),] %>% group_by(subject) %>% summarize(nativelanguage = gsub(" ","",tolower(response)))
ggplot(data = summarized_data, aes(nativelanguage,fill=nativelanguage)) +
  geom_bar() +
  labs(x="Native Language",y="frequency",title="Native Language histogram")+
  scale_fill_brewer() +
  theme_bw()
```


###Education
```{r}
summarized_data = complete_data[grepl("education",gsub(" ","",complete_data$question)),] %>% group_by(subject) %>% summarize(education = gsub(" ","",response))
summarized_data$education = factor(summarized_data$education,c("Didnotgraduatehighschool","Highschooldiploma","Somecollege,nodegree","AssociatesDegree","BachelorsDegree","Somegraduateschool,nodegree","MastersDegree","Doctorate,M.D.,etc."))
ggplot(data = summarized_data, aes(education,fill=education)) +
  geom_bar() +
  labs(x="Education Level",y="frequency",title="Education histogram")+
  scale_fill_brewer() +
  theme_bw()

```

###Highest math course:
```{r}
complete_data[grepl("mathclass",gsub(" ","",complete_data$question)),]$response
```

Should we try to code this? If so, how?

###Pen and paper?

```{r}
summarized_data = complete_data[grepl("penandpaper",gsub(" ","",complete_data$question)),] %>% group_by(subject) %>% summarize(penandpaper = gsub(" ","",tolower(response))) %>% mutate(penandpaper = ifelse(grepl('yes',penandpaper),'Yes',ifelse(grepl('no',penandpaper),'No','Other')))
ggplot(data = summarized_data, aes(penandpaper,fill=penandpaper)) +
  geom_bar() +
  labs(x="Did you use pen and paper?",y="frequency",title="Pen and paper histogram")+
  scale_fill_brewer() +
  theme_bw()
```

###Feel you understood?

```{r}
summarized_data = complete_data[grepl("feelyouunderstood",gsub(" ","",complete_data$question)),] %>% group_by(subject) %>% summarize(feelyouunderstood = gsub(" ","",response))
ggplot(data = summarized_data, aes(feelyouunderstood,fill=feelyouunderstood)) +
  geom_bar() +
  labs(x="Do you feel you understood the concepts in this HIT?",y="frequency",title="Feel you understood? histogram")+
  scale_fill_brewer() +
  theme_bw()
```

###Feel you learned something?

```{r}
summarized_data = complete_data[grepl("feelyoulearnedsomething",gsub(" ","",complete_data$question)),] %>% group_by(subject) %>% summarize(feelyoulearnedsomething = gsub(" ","",response))
ggplot(data = summarized_data, aes(feelyoulearnedsomething,fill=feelyoulearnedsomething)) +
  geom_bar() +
  labs(x="Do you feel you learned something from this HIT?",y="frequency",title="Feel you learned something? histogram")+
  scale_fill_brewer() +
  theme_bw()
```


Subject exclusion
----------------------
Exclude subjects who responded 4 or higher on familiarity with modular arithmetic or mathematical groups: they know too much

```{r}
complete_unfiltered_data = complete_data
subjects_to_exclude = unique(complete_data[grepl("Howfamiliarareyou",gsub(" ","",complete_data$question)) & (grepl("4",complete_data$response) | grepl("5",complete_data$response)),]$subject)

complete_data = complete_unfiltered_data %>% filter(!(subject %in% subjects_to_exclude))


```


Statistics
---------------------

Change dummy coding to compare hybrid and polygon to modular.
```{r}
contrasts(complete_data$condition) = cbind(c(0,0,1),c(1,0,0))
colnames(contrasts(complete_data$condition)) = c('polygon','hybrid')
contrasts(complete_data$condition) 
```



##Operation
train
```{r}
gmod = glmer(score_strict ~ condition  + (1|subject), family="binomial", data=complete_data[grepl("Remember,toperform",gsub(" ","",complete_data$question)),])
summary(gmod)

```

test
```{r}
gmod = glmer(score_strict ~ condition  + (1|subject), family="binomial", data=complete_data[!(grepl("identity",gsub(" ","",complete_data$question)) | grepl("inverse",gsub(" ","",complete_data$question)) | grepl("generator",gsub(" ","",complete_data$question))) & (grepl("nonagon",gsub(" ","",complete_data$question)) | grepl("+<sub>9",gsub(" ","",complete_data$question)) ),]) 
summary(gmod)
```

The methods do not differ significantly for learning the operation.

##Inverses
Inverse train score model:
```{r}


# aggregated_data = complete_data[grepl("Remember,theinverse",gsub(" ","",complete_data$question)),] %>% mutate(correct_response=gsub(" ","",correct_response)) %>% select(score_strict,condition,correct_response,subject) %>% spread(correct_response,score_strict) %>% mutate(score = `0`+`2`+`3`+`4`+`5`)
#   
# ggplot(aggregated_data,aes(condition,score,fill=condition)) +
#     geom_boxplot() +
#     theme_bw() +
#     labs(x="Condition",y="Inverse Train Accuracy")

changed_data = complete_data[grepl("Remember,theinverse",gsub(" ","",complete_data$question)),] %>% mutate(is_0 = grepl('0',correct_response))

mod = glmer(score_strict ~ condition + (1|subject), family="binomial", data=complete_data[grepl("Remember,theinverse",gsub(" ","",complete_data$question)),]) #fitting failed

mod1 = glmer(score_strict ~ condition *is_0 +  (1|subject), family="binomial", data=changed_data) 
summary(mod1)

```

Is this effect driven by performance on the "inverse of 0" question? 
```{r}
# ggplot(aggregated_data,aes(condition,`0`,fill=condition)) +
#     geom_boxplot() +
#     theme_bw() +
#     labs(x="Condition",y="Inverse of 0 Train Accuracy")

mod0 = glm(score_strict ~ condition, family='binomial', data=complete_data[grepl("Whatistheinverseof0",gsub(" ","",complete_data$question)),]) #Test only the results on the inverse of 0 question
summary(mod0)

gmodnz = glmer(score_strict ~ condition  + (1|subject), family="binomial", data=complete_data[grepl("Remember,theinverse",gsub(" ","",complete_data$question)) & !grepl("Whatistheinverseof0",gsub(" ","",complete_data$question)) ,]) #Test results on the non-zero questions
summary(gmodnz)
```

The polygon group performed significantly better on the "inverse of 0" question, but the groups were not significantly different on the other two conditions.

Inverse test score model:
```{r}


# aggregated_data = complete_data[grepl("Whatistheinverse",gsub(" ","",complete_data$question)) & !grepl("Remember,theinverse",gsub(" ","",complete_data$question)),] %>% mutate(correct_response=gsub(" ","",correct_response)) %>% select(score_strict,condition,correct_response,subject) %>% spread(correct_response,score_strict) %>% mutate(score = `4`+`7`+`0`)
#   
# ggplot(aggregated_data,aes(condition,score,fill=condition)) +
#     geom_boxplot() +
#     theme_bw() +
#     labs(x="Condition",y="Inverse Test Accuracy")




gmod = glmer(score_strict ~ condition + (1|subject),family="binomial", data=complete_data[grepl("Whatistheinverse",gsub(" ","",complete_data$question)) & !grepl("Remember,theinverse",gsub(" ","",complete_data$question)) ,])
summary(gmod)


#Testing if inverse of 0 still causes problems, or if they learned from their errors
mod0 = glm(score_strict ~ condition, family='binomial', data=complete_data[grepl("Whatistheinverseof0",gsub(" ","",complete_data$question)) & !grepl("Remember,theinverse",gsub(" ","",complete_data$question)),]) #Test only the results on the inverse of 0 question
summary(mod0)

#
changed_data = complete_data[grepl("Whatistheinverse",gsub(" ","",complete_data$question)) & !grepl("Remember,theinverse",gsub(" ","",complete_data$question)), ] %>% mutate(is_0 = grepl('0',correct_response))
gmodint = glmer(score_strict ~ condition*is_0 + (1|subject),family="binomial", data=changed_data)
summary(gmodint)
```


  
Inverse of 1, inverse of x questions
```{r}
ggplot(complete_data[inverse_formula_scores$row.names,],aes(condition,score_strict,fill=condition)) +
    geom_boxplot() +
    theme_bw() +
    labs(x="Condition",y="Accuracy")



gmod_strict = glmer(score_strict ~ condition+ (1|subject), family="binomial",data=complete_data[inverse_formula_scores$row.names,])
summary(gmod_strict)
```

Does it make a difference using the non-strict score? (Including half credit for answers that made small errors like flipping a sign, "x-n" instead of "n-x", etc.)
```{r}
ggplot(complete_data[inverse_formula_scores$row.names,],aes(condition,score,fill=condition)) +
    geom_boxplot() +
    theme_bw() +
    labs(x="Condition",y="Score w/ Partial Credit")

gmod_partial_credit = glmer(score ~ condition+ (1|subject), family="binomial",data=complete_data[inverse_formula_scores$row.names,])
summary(gmod_partial_credit)
```

##Generators

Training (Order 6):
```{r}
ggplot(complete_data[grepl("generatorunder",gsub(" ","",complete_data$question)) & (grepl("hexagon",gsub(" ","",complete_data$question)) | grepl("+<sub>6",gsub(" ","",complete_data$question)) ),],aes(condition,score_strict,fill=condition)) +
    geom_boxplot() +
    theme_bw() +
    labs(x="Condition",y="Generator Training Accuracy")

temp_data = complete_data[grepl("generatorunder",gsub(" ","",complete_data$question)) & (grepl("hexagon",gsub(" ","",complete_data$question)) | grepl("+<sub>6",gsub(" ","",complete_data$question)) ),]
temp_data = temp_data %>% mutate(generator = (gsub(" ","",correct_response)) == "Yes")

mod = glmer(score_strict ~ condition + generator + (1|subject),family="binomial", data=temp_data)
summary(mod)
```


Testing (order 9):
```{r}
ggplot(complete_data[grepl("generatorunder",gsub(" ","",complete_data$question)) & (grepl("nonagon",gsub(" ","",complete_data$question)) | grepl("+<sub>9",gsub(" ","",complete_data$question)) ),],aes(condition,score_strict,fill=condition)) +
    geom_boxplot() +
    theme_bw() +
    labs(x="Condition",y="Generators order 9 Test Accuracy")

mod = lmer(score_strict ~ condition + (1|subject), data=complete_data[grepl("generatorunder",gsub(" ","",complete_data$question)) & (grepl("nonagon",gsub(" ","",complete_data$question)) | grepl("+<sub>9",gsub(" ","",complete_data$question)) ),])
summary(mod)
```

```{r}
temp_data = complete_data[grepl("generatorunder",gsub(" ","",complete_data$question)) & (grepl("nonagon",gsub(" ","",complete_data$question)) | grepl("+<sub>9",gsub(" ","",complete_data$question)) ),]
temp_data = temp_data %>% mutate(number=ifelse(grepl("2",temp_data$question),2,ifelse(grepl("3",temp_data$question),3,ifelse(grepl("5",temp_data$question),5,6)))) 
temp_data$number = factor(temp_data$number)
temp_data$subject = factor(temp_data$subject)
temp_data = temp_data %>% mutate(generator=ifelse(number==2 | number==5,TRUE,FALSE))
mod = glmer(score_strict ~ condition+ generator+(1|subject), data=temp_data,family=binomial)
summary(mod)

#EXPLORATORY ANALYSIS
mod1 = glmer(score_strict ~ condition *generator+(1|subject), data=temp_data,family=binomial)
summary(mod1)

anova(mod,mod1)
```

It appears that there is a significant positive effect of polygon condition on ability to correctly test whether something is a generator, and a highly significant negative effect of the element actually being a generator. Subjects show a strong bias toward saying that an element is not a generator when it is.

Order n T/F:
```{r}
ggplot(complete_data[grepl("Trueorfalse",gsub(" ","",complete_data$question)),],aes(condition,score_strict,fill=condition)) +
    geom_boxplot() +
    theme_bw() +
    labs(x="Condition",y="Generators order n T/F Accuracy")


gmod = glmer(score_strict ~ condition + (1|subject),family="binomial", data=complete_data[grepl("Trueorfalse",gsub(" ","",complete_data$question)),])
summary(gmod)
```

The polygon group was significantly worse at the order n T/F questions.

Order n A/S/N:
```{r}
ggplot(complete_data[grepl("always,sometimes,ornever",gsub(" ","",complete_data$question)),],aes(condition,score_strict,fill=condition)) +
    geom_boxplot() +
    theme_bw() +
    labs(x="Condition",y="Generators order n A/S/N Accuracy")


gmod = glmer(score_strict ~ condition + (1|subject),family="binomial", data=complete_data[grepl("always,sometimes,ornever",gsub(" ","",complete_data$question)),])
summary(gmod)
```


##RT

```{r}
complete_data$rt = complete_data$rt/1000 #convert from ms to s
```


```{r}
rt_mod = lmer(rt ~ condition + (1|subject),data=complete_data)
summary(rt_mod)
```

No significant overall difference, but this is averaged across all questions, so there may be a larger effect in some problem types. Try just the operation training:

```{r}
rt_mod = lmer(rt ~ condition+ (1|subject),data=complete_data[grepl("Remember,toperform",gsub(" ","",complete_data$question)),])

summary(rt_mod)
```

Interesting, but not entirely surprising. Polygon and hybrid conditions were slower at performing the early operation.

##Question by question

```{r}
polygon_question = vector()
modular_question = vector()
hybrid_question = vector()
polygon_question_aggregate_scores = vector()
modular_question_aggregate_scores = vector()
hybrid_question_aggregate_scores = vector()
num_subjects = length(unique(complete_data$subject))
for (subj_i in 1:num_subjects) {
  this_subj_data = complete_data[complete_data$subject == subj_i,]
  this_subj_condition = this_subj_data[1,]$condition
  index = 1
  prob_i = 1
  offset = 0 
  while (prob_i <= length(this_subj_data$question)) {
    if (prob_i==(11+offset) && grepl("Remember,toperform",gsub(" ","",this_subj_data[prob_i,]$question)))   { #If subject had to repeat training
      print(subj_i)
      prob_i = prob_i+10      
      offset = offset + 10
    } 
    if (prob_i == 16+offset && grepl("prompt",this_subj_data[prob_i,]$condition)) {
      prob_i = prob_i+1
      offset = offset + 1
    }
    if (prob_i == 20+offset && grepl("prompt",this_subj_data[prob_i,]$condition)) {
      prob_i = prob_i+1
      offset = offset + 1
    }
    if (prob_i == 58+offset){ #Skip background questions
      break
    }
    
    if (this_subj_condition == 'polygon') {
      this_problem_score = this_subj_data[prob_i,]$score_strict
      if (is.na(polygon_question_aggregate_scores[index])) {
        polygon_question_aggregate_scores[index] = this_problem_score 
        polygon_question[index] = this_subj_data[prob_i,]$question
      }
      else {
        polygon_question_aggregate_scores[index] = polygon_question_aggregate_scores[index] + this_problem_score 
      }
    } 
    else if (this_subj_condition == 'modular') {
      this_problem_score = this_subj_data[prob_i,]$score_strict
      if (is.na(modular_question_aggregate_scores[index])) {
        modular_question_aggregate_scores[index] = this_problem_score 
        modular_question[index] = this_subj_data[prob_i,]$question
      }
      else {
        modular_question_aggregate_scores[index] = modular_question_aggregate_scores[index] + this_problem_score 
      }
      
    }
    else {
       this_problem_score = this_subj_data[prob_i,]$score_strict
      if (is.na(hybrid_question_aggregate_scores[index])) {
        hybrid_question_aggregate_scores[index] = this_problem_score 
        hybrid_question[index] = this_subj_data[prob_i,]$question
      }
      else {
        hybrid_question_aggregate_scores[index] = hybrid_question_aggregate_scores[index] + this_problem_score 
      }
           
      
      
    }
    
    prob_i = prob_i+1
    index = index + 1
  }
}
```

```{r}
aggregate_score_data = data.frame(condition=c(rep('polygon',length(polygon_question_aggregate_scores)),rep('modular',length(modular_question_aggregate_scores)),rep('hybrid',length(modular_question_aggregate_scores))),score=c(polygon_question_aggregate_scores,modular_question_aggregate_scores,hybrid_question_aggregate_scores),question_index=rep(1:length(polygon_question_aggregate_scores),3))



aggregate_score_data$percent_correct = rep(0,length(aggregate_score_data$score))

aggregate_score_data[aggregate_score_data$condition == 'hybrid',]$percent_correct= aggregate_score_data[aggregate_score_data$condition == 'hybrid',]$score/length(unique(complete_data[complete_data$condition == 'hybrid',]$subject))
aggregate_score_data[aggregate_score_data$condition == 'modular',]$percent_correct= aggregate_score_data[aggregate_score_data$condition == 'modular',]$score/length(unique(complete_data[complete_data$condition == 'modular',]$subject))
aggregate_score_data[aggregate_score_data$condition == 'polygon',]$percent_correct= aggregate_score_data[aggregate_score_data$condition == 'polygon',]$score/length(unique(complete_data[complete_data$condition == 'polygon',]$subject))

ggplot(data=aggregate_score_data,aes(question_index,percent_correct,fill=condition)) +
  geom_bar(stat='identity',position='dodge',width=0.5) +
  theme_bw()
```


Lab Meeting Presentation Stuff
----------------------
```{r}
sem <- function(x) {sd(x, na.rm=TRUE) / sqrt(length(x))}
theme_set(theme_bw())
```


Operation order 6:
```{r}
summarized_data = complete_data[grepl("Remember,toperform",gsub(" ","",complete_data$question)),] %>% group_by(subject) %>% summarize(percent_correct = mean(score_strict),condition=head(condition,n=1)) %>% group_by(condition) %>% summarize(percent_correct.mean = mean(percent_correct),percent_correct.sem = sem(percent_correct))

ggplot(data=summarized_data,aes(condition,percent_correct.mean,fill=condition)) +
  geom_bar(stat="identity") +
  geom_errorbar(aes(ymax=percent_correct.mean+percent_correct.sem,ymin=percent_correct.mean-percent_correct.sem,width=0.25)) +
  annotate("text",x=1.5,y=1.05,label='p = 0.53',alpha=0.5)+
  annotate("text",x=2.5,y=1.05,label='p = 0.43',alpha=0.5)+
  ggtitle("Operation Order 6 Results")
```


Operation order 9:
```{r}
summarized_data = complete_data[!(grepl("identity",gsub(" ","",complete_data$question)) | grepl("inverse",gsub(" ","",complete_data$question)) | grepl("generator",gsub(" ","",complete_data$question))) & (grepl("nonagon",gsub(" ","",complete_data$question)) | grepl("+<sub>9",gsub(" ","",complete_data$question)) ),] %>% group_by(subject) %>% summarize(percent_correct = mean(score_strict),condition=head(condition,n=1)) %>% group_by(condition) %>% summarize(percent_correct.mean = mean(percent_correct),percent_correct.sem = sem(percent_correct))

ggplot(data=summarized_data,aes(condition,percent_correct.mean,fill=condition)) +
  geom_bar(stat="identity") +
  geom_errorbar(aes(ymax=percent_correct.mean+percent_correct.sem,ymin=percent_correct.mean-percent_correct.sem,width=0.25)) +
  annotate("text",x=1.5,y=1.05,label='p = 0.31',alpha=0.5)+
  annotate("text",x=2.5,y=1.05,label='p = 0.51',alpha=0.5)+
  ggtitle("Operation Order 9 Results")
```


Inverse train:
```{r}
summarized_data = complete_data[grepl("Remember,theinverse",gsub(" ","",complete_data$question)),] %>% mutate(is_0 = grepl('0',correct_response)) %>% group_by(subject,condition,is_0) %>% summarize(percent_correct = mean(score_strict)) %>% group_by(condition,is_0) %>% summarize(percent_correct.mean = mean(percent_correct),percent_correct.sem = sem(percent_correct))


ggplot(data=summarized_data,aes(is_0,percent_correct.mean,fill=condition)) +
  geom_bar(stat="identity",position="dodge") +
  geom_errorbar(aes(ymax=percent_correct.mean+percent_correct.sem,ymin=percent_correct.mean-percent_correct.sem),position="dodge") +
  annotate("text",x=0.83,y=1.03,label='ns',alpha=0.5)+
  annotate("path",x=c(1.05,1.05,1.3,1.3),y=c(0.98,1.0,1.0,0.98),alpha=0.5)+
  annotate("text",x=1.19,y=1.01,label='**',alpha=0.5)+
  annotate("path",x=c(0.7,0.7,0.95,0.95),y=c(0.98,1.0,1.0,0.98),alpha=0.5)+
  annotate("text",x=1.82,y=1.01,label='***',alpha=0.5)+
  annotate("path",x=c(1.7,1.7,1.95,1.95),y=c(0.98,1.0,1.0,0.98),alpha=0.5)+
  annotate("text",x=2.19,y=1.01,label='***',alpha=0.5)+
  annotate("path",x=c(2.05,2.05,2.3,2.3),y=c(0.98,1.0,1.0,0.98),alpha=0.5)+
  ggtitle("Inverse Order 6 Results")
```


Inverse test:
```{r}
summarized_data = complete_data[grepl("Whatistheinverse",gsub(" ","",complete_data$question)) & !grepl("Remember,theinverse",gsub(" ","",complete_data$question)),] %>% mutate(is_0 = grepl('0',correct_response)) %>% group_by(subject,condition,is_0) %>% summarize(percent_correct = mean(score_strict)) %>% group_by(condition,is_0) %>% summarize(percent_correct.mean = mean(percent_correct),percent_correct.sem = sem(percent_correct))

ggplot(data=summarized_data,aes(is_0,percent_correct.mean,fill=condition)) +
  geom_bar(stat="identity",position="dodge") +
  geom_errorbar(aes(ymax=percent_correct.mean+percent_correct.sem,ymin=percent_correct.mean-percent_correct.sem),position="dodge") +
  annotate("text",x=0.83,y=1.03,label='ns',alpha=0.5)+
  annotate("path",x=c(1.05,1.05,1.3,1.3),y=c(0.98,1.0,1.0,0.98),alpha=0.5)+
  annotate("text",x=1.19,y=1.01,label='*',alpha=0.5)+
  annotate("path",x=c(0.7,0.7,0.95,0.95),y=c(0.98,1.0,1.0,0.98),alpha=0.5)+
  annotate("text",x=1.82,y=1.01,label='***',alpha=0.5)+
  annotate("path",x=c(1.7,1.7,1.95,1.95),y=c(0.98,1.0,1.0,0.98),alpha=0.5)+
  annotate("text",x=2.19,y=1.01,label='***',alpha=0.5)+
  annotate("path",x=c(2.05,2.05,2.3,2.3),y=c(0.98,1.0,1.0,0.98),alpha=0.5)+
  ggtitle("Inverse Order 9 Results")
```



Inverse of 0:
```{r}
# summarized_data = complete_data[grepl("Remember,theinverse",gsub(" ","",complete_data$question)),] %>% filter(grepl("0",correct_response)) %>% group_by(subject,condition) %>% summarize(percent_correct = mean(score_strict)) %>% group_by(condition) %>% summarize(percent_correct.mean = mean(percent_correct),percent_correct.sem = sem(percent_correct))
# 
# ggplot(data=summarized_data,aes(condition,percent_correct.mean,fill=condition)) +
#   geom_bar(stat="identity",position="dodge") +
#   geom_errorbar(aes(ymax=percent_correct.mean+percent_correct.sem,ymin=percent_correct.mean-percent_correct.sem,width=0.25),position="dodge") +
# #  annotate("text",x=1.5,y=1.0,label='',alpha=0.5)+
#   ggtitle("Inverse of 0 Results (Order 6)")
```

```{r}
# summarized_data = complete_data[grepl("Whatistheinverse",gsub(" ","",complete_data$question)) & !grepl("Remember,theinverse",gsub(" ","",complete_data$question)), ] %>% filter(grepl("0",correct_response)) %>% group_by(subject,condition) %>% summarize(percent_correct = mean(score_strict)) %>% group_by(condition) %>% summarize(percent_correct.mean = mean(percent_correct),percent_correct.sem = sem(percent_correct))
# 
# ggplot(data=summarized_data,aes(condition,percent_correct.mean,fill=condition)) +
#   geom_bar(stat="identity",position="dodge") +
#   geom_errorbar(aes(ymax=percent_correct.mean+percent_correct.sem,ymin=percent_correct.mean-percent_correct.sem,width=0.25),position="dodge") +
# #  annotate("text",x=1.5,y=1.0,label='',alpha=0.5)+
#   ggtitle("Inverse of 0 Results (Order 9)")
```

Inverse of 1, x:

```{r}


summarized_data = complete_data[grepl("formula",gsub(" ","",complete_data$question)) & grepl("1",gsub(" ","",complete_data$question)),] %>% group_by(subject,condition) %>% summarize(percent_correct = mean(score_strict)) %>% group_by(condition) %>% summarize(percent_correct.mean = mean(percent_correct),percent_correct.sem = sem(percent_correct))

ggplot(data=summarized_data,aes(condition,percent_correct.mean,fill=condition)) +
  geom_bar(stat="identity",position="dodge") +
  geom_errorbar(aes(ymax=percent_correct.mean+percent_correct.sem,ymin=percent_correct.mean-percent_correct.sem,width=0.25),position="dodge") +
  ggtitle("Inverse of 1 Results")

```

```{r}


summarized_data = complete_data[grepl("formula",gsub(" ","",complete_data$question)) & grepl("x",gsub(" ","",complete_data$question)),] %>% group_by(subject,condition) %>% summarize(percent_correct = mean(score_strict)) %>% group_by(condition) %>% summarize(percent_correct.mean = mean(percent_correct),percent_correct.sem = sem(percent_correct))

ggplot(data=summarized_data,aes(condition,percent_correct.mean,fill=condition)) +
  geom_bar(stat="identity",position="dodge") +
  geom_errorbar(aes(ymax=percent_correct.mean+percent_correct.sem,ymin=percent_correct.mean-percent_correct.sem,width=0.25),position="dodge") +
#  annotate("text",x=1.5,y=1.0,label='',alpha=0.5)+
  ggtitle("Inverse of x Results")

```

```{r}
summarized_data = complete_data[grepl("formula",gsub(" ","",complete_data$question)),] %>% group_by(subject,condition) %>% summarize(percent_correct = mean(score_strict)) %>% group_by(condition) %>% summarize(percent_correct.mean = mean(percent_correct),percent_correct.sem = sem(percent_correct))

ggplot(data=summarized_data,aes(condition,percent_correct.mean,fill=condition)) +
  geom_bar(stat="identity",position="dodge") +
  geom_errorbar(aes(ymax=percent_correct.mean+percent_correct.sem,ymin=percent_correct.mean-percent_correct.sem,width=0.25),position="dodge") +
  annotate("text",x=2,y=1.0,label='all ns',alpha=0.5)+
  ggtitle("Inverse of 1, x Results")

```





Generator training:

```{r}
summarized_data = complete_data[grepl("generatorunder",gsub(" ","",complete_data$question)) & (grepl("hexagon",gsub(" ","",complete_data$question)) | grepl("+<sub>6",gsub(" ","",complete_data$question)) ),] %>% mutate(generator = (gsub(" ","",correct_response)) == "Yes") %>% group_by(subject,condition,generator) %>% summarize(percent_correct = mean(score_strict)) %>% group_by(condition,generator) %>% summarize(percent_correct.mean = mean(percent_correct),percent_correct.sem = sem(percent_correct))

ggplot(data=summarized_data,aes(generator,percent_correct.mean,fill=condition)) +
  geom_bar(stat="identity",position="dodge") +
  geom_errorbar(aes(ymax=percent_correct.mean+percent_correct.sem,ymin=percent_correct.mean-percent_correct.sem),position="dodge") +
  annotate("text",x=1.5,y=1.0,label='all ns',alpha=0.5)+
  ggtitle("Generator Order 6 Results")
```

Generator testing:

```{r}
temp_data = complete_data[grepl("generatorunder",gsub(" ","",complete_data$question)) & (grepl("nonagon",gsub(" ","",complete_data$question)) | grepl("+<sub>9",gsub(" ","",complete_data$question)) ),]

summarized_data = temp_data %>% mutate(number=ifelse(grepl("2",question),2,ifelse(grepl("3",question),3,ifelse(grepl("5",question),5,6)))) %>% mutate(generator=ifelse(number==2 | number==5,TRUE,FALSE))%>% group_by(subject,condition,generator) %>% summarize(percent_correct = mean(score_strict)) %>% group_by(condition,generator) %>% summarize(percent_correct.mean = mean(percent_correct),percent_correct.sem = sem(percent_correct))

ggplot(data=summarized_data,aes(generator,percent_correct.mean,fill=condition)) +
  geom_bar(stat="identity",position="dodge") +
  geom_errorbar(aes(ymax=percent_correct.mean+percent_correct.sem,ymin=percent_correct.mean-percent_correct.sem),position="dodge") +
  annotate("text",x=0.83,y=1.03,label='ns',alpha=0.5)+
  annotate("path",x=c(1.05,1.05,1.3,1.3),y=c(0.98,1.0,1.0,0.98),alpha=0.5)+
  annotate("text",x=1.18,y=1.03,label='ns',alpha=0.5)+
  annotate("path",x=c(0.7,0.7,0.95,0.95),y=c(0.98,1.0,1.0,0.98),alpha=0.5)+
  annotate("text",x=1.82,y=1.01,label='***',alpha=0.5)+
  annotate("path",x=c(1.7,1.7,1.95,1.95),y=c(0.98,1.0,1.0,0.98),alpha=0.5)+
  annotate("text",x=2.19,y=1.01,label='**',alpha=0.5)+
  annotate("path",x=c(2.05,2.05,2.3,2.3),y=c(0.98,1.0,1.0,0.98),alpha=0.5)+
  ggtitle("Generator Order 9 Results")
```

Generator T/F:

```{r}
summarized_data = complete_data[grepl("Trueorfalse",gsub(" ","",complete_data$question)),] %>% group_by(subject,condition) %>% summarize(percent_correct = mean(score_strict)) %>% group_by(condition) %>% summarize(percent_correct.mean = mean(percent_correct),percent_correct.sem = sem(percent_correct))

ggplot(data=summarized_data,aes(condition,percent_correct.mean,fill=condition)) +
  geom_bar(stat="identity",position="dodge") +
  geom_errorbar(aes(ymax=percent_correct.mean+percent_correct.sem,ymin=percent_correct.mean-percent_correct.sem),position="dodge") +
  annotate("text",x=1.5,y=1.0,label='p = 0.21',alpha=0.5)+
  annotate("text",x=2.5,y=1.0,label='p = 0.003',alpha=0.5)+
  ggtitle("Generator T/F Results")
```


Generator A/S/N:

```{r}
summarized_data = complete_data[grepl("always,sometimes,ornever",gsub(" ","",complete_data$question)),] %>% group_by(subject,condition) %>% summarize(percent_correct = mean(score_strict)) %>% group_by(condition) %>% summarize(percent_correct.mean = mean(percent_correct),percent_correct.sem = sem(percent_correct))

ggplot(data=summarized_data,aes(condition,percent_correct.mean,fill=condition)) +
  geom_bar(stat="identity",position="dodge") +
  geom_errorbar(aes(ymax=percent_correct.mean+percent_correct.sem,ymin=percent_correct.mean-percent_correct.sem),position="dodge") +
  annotate("text",x=1.5,y=1.0,label='p = 0.83',alpha=0.5)+
  annotate("text",x=2.5,y=1.0,label='p = 0.97',alpha=0.5)+
  ggtitle("Generator A/S/N Results")
```

