---
title: "fyp_meta_analysis"
author: "AndrewLampinen"
date: "May 19, 2016"
output: html_document
---
```{r}
library(metafor)
library(crop)
```

```{r}
fyp_1 = read.csv('fyp_1_selected_bootstrap_estimates.csv')
fyp_2 = read.csv('fyp_2_selected_bootstrap_estimates.csv')
fyp_3 = read.csv('fyp_3_selected_bootstrap_estimates.csv')
fyp_1 = data.frame(lapply(fyp_1,function(x) {gsub("polygonTRUE","conditionpolygon", x)})) #variable name consistency
names(fyp_1) = c('Ignore','Variable','logOR','se') 
fyp_1$logOR = as.numeric(levels(fyp_1$logOR)[fyp_1$logOR])
fyp_1$se = as.numeric(levels(fyp_1$se)[fyp_1$se])
names(fyp_2) = c('Ignore','Variable','logOR','se')
names(fyp_3) = c('Ignore','Variable','logOR','se')
```


```{r}
study_labels = c('Exp. 1','Exp. 2','Exp. 3')
for (var in fyp_1$Variable) {
  print(var)
  logOR = c(fyp_1[levels(fyp_1$Variable)[fyp_1$Variable] == var,]$logOR,fyp_2[levels(fyp_2$Variable)[fyp_2$Variable] == var,]$logOR,fyp_3[levels(fyp_3$Variable)[fyp_3$Variable] == var,]$logOR)
  se =  c(fyp_1[levels(fyp_1$Variable)[fyp_1$Variable] == var,]$se,fyp_2[levels(fyp_2$Variable)[fyp_2$Variable] == var,]$se,fyp_3[levels(fyp_3$Variable)[fyp_3$Variable] == var,]$se)
  n.e = c(50,50,100) #num subjects in experimental (polygon or hybrid)
  n.c = c(50,50,100) #num subjects in comparison (modular)
  or.meta = rma(yi=logOR,sei=se,measure="OR",n2i=n.e,n1i=n.c)
  print(or.meta)

  pdf(file = paste('./meta_plots/',gsub('\\.','_',var),'.pdf',sep= ''),width=6,height=6)
  forest(or.meta,slab=study_labels)
  dev.off.crop()
  cat('\n\n')
}

study_labels = c('Exp. 2','Exp. 3')
for (var in fyp_2$Variable) {
  if (var %in% fyp_1$Variable) {
    next
  }
  print(var)
  logOR = c(fyp_2[levels(fyp_2$Variable)[fyp_2$Variable] == var,]$logOR,fyp_3[levels(fyp_3$Variable)[fyp_3$Variable] == var,]$logOR)
  se = c(fyp_2[levels(fyp_2$Variable)[fyp_2$Variable] == var,]$se,fyp_3[levels(fyp_3$Variable)[fyp_3$Variable] == var,]$se)
  n.e = c(50,100) #num subjects in experimental (polygon or hybrid)
  n.c = c(50,100) #num subjects in comparison (modular)
  or.meta = rma(yi=logOR,sei=se,measure="OR",n2i=n.e,n1i=n.c)
  print(or.meta)
  pdf(file = paste('./meta_plots/',gsub('\\.','_',var),'.pdf',sep= ''),width=6,height=6)
  forest(or.meta,slab=study_labels)
  dev.off.crop()
  cat('\n\n')
}
```

aggregating across group orders
```{r}
study_labels = c('Exp. 1 order 6','Exp. 1 order 9','Exp. 2 order 6','Exp. 2 order 9','Exp. 3 order 6','Exp. 3 order 9')
for (var in c('question_typegenerator_true_%i.conditionpolygon','question_typegenerator_false_%i.conditionpolygon','question_typeinverse_nonzero_%i.conditionpolygon')) {
  print(var)
  logOR = c(fyp_1[levels(fyp_1$Variable)[fyp_1$Variable] == sprintf(var,6),]$logOR,fyp_1[levels(fyp_1$Variable)[fyp_1$Variable] == sprintf(var,9),]$logOR,fyp_2[levels(fyp_2$Variable)[fyp_2$Variable] == sprintf(var,6),]$logOR,fyp_2[levels(fyp_2$Variable)[fyp_2$Variable] == sprintf(var,9),]$logOR,fyp_3[levels(fyp_3$Variable)[fyp_3$Variable] == sprintf(var,6),]$logOR,fyp_3[levels(fyp_3$Variable)[fyp_3$Variable] == sprintf(var,9),]$logOR)
  se = c(fyp_1[levels(fyp_1$Variable)[fyp_1$Variable] == sprintf(var,6),]$se,fyp_1[levels(fyp_1$Variable)[fyp_1$Variable] == sprintf(var,9),]$se,fyp_2[levels(fyp_2$Variable)[fyp_2$Variable] == sprintf(var,6),]$se,fyp_2[levels(fyp_2$Variable)[fyp_2$Variable] == sprintf(var,9),]$se,fyp_3[levels(fyp_3$Variable)[fyp_3$Variable] == sprintf(var,6),]$se,fyp_3[levels(fyp_3$Variable)[fyp_3$Variable] == sprintf(var,9),]$se)
  n.e = c(50,50,50,50,100,100) #num subjects in experimental (polygon or hybrid)
  n.c = c(50,50,50,50,100,100) #num subjects in comparison (modular)
  or.meta = rma(yi=logOR,sei=se,measure="OR",n2i=n.e,n1i=n.c)
  print(or.meta)

pdf(file = paste('./meta_plots/',gsub('\\.','_',var),'_aggregated.pdf',sep= ''),width=6,height=6)
  forest(or.meta,slab=study_labels)
dev.off.crop()
  cat('\n\n')
}

study_labels = c('Exp. 2 order 6','Exp. 2 order 9','Exp. 3 order 6','Exp. 3 order 9')
for (var in c('question_typegenerator_true_%i.conditionhybrid','question_typegenerator_false_%i.conditionhybrid','question_typeinverse_nonzero_%i.conditionhybrid','question_typeinverse_zero_%i.conditionhybrid','question_typeinverse_nonzero_%i.conditionpolygon')) {
  print(var)
  logOR = c(fyp_2[levels(fyp_2$Variable)[fyp_2$Variable] == sprintf(var,6),]$logOR,fyp_2[levels(fyp_2$Variable)[fyp_2$Variable] == sprintf(var,9),]$logOR,fyp_3[levels(fyp_3$Variable)[fyp_3$Variable] == sprintf(var,6),]$logOR,fyp_3[levels(fyp_3$Variable)[fyp_3$Variable] == sprintf(var,9),]$logOR)
  se = c(fyp_2[levels(fyp_2$Variable)[fyp_2$Variable] == sprintf(var,6),]$se,fyp_2[levels(fyp_2$Variable)[fyp_2$Variable] == sprintf(var,9),]$se,fyp_3[levels(fyp_3$Variable)[fyp_3$Variable] == sprintf(var,6),]$se,fyp_3[levels(fyp_3$Variable)[fyp_3$Variable] == sprintf(var,9),]$se)
  n.e = c(50,50,100,100) #num subjects in experimental (polygon or hybrid)
  n.c = c(50,50,100,100) #num subjects in comparison (modular)
  or.meta = rma(yi=logOR,sei=se,measure="OR",n2i=n.e,n1i=n.c)
  print(or.meta)

pdf(file = paste('./meta_plots/',gsub('\\.','_',var),'_aggregated.pdf',sep= ''),width=6,height=6)
  forest(or.meta,slab=study_labels)
dev.off.crop()
  cat('\n\n')
}
```

